name: Docker Infra
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image:  node:latest
    steps:
      - name: log node version
        run: node -v
      - name: step with docker
        uses: docker://node:latest
        with: 
          entrypoint: '/bin/echo'
          args: 'hello world'
      - name: step with docker
        uses: docker://node:latest
        with: 
          entrypoint: '/bin/ls'
          args: '-a'
      - name: step with docker
        uses: docker://node:latest
        with: 
          entrypoint: '/usr/local/bin/node'
          args: '-v'
  # deploy-app-docker:
  #   runs-on: ubuntu-latest
  #   services:
  #     app: 
  #       image: alialaa17/node-api
  #       ports:
  #         - 3001:3000
  #     mongo:
  #       image: mongo
  #       ports:
  #         - "27017:27017"
  #   steps:
  #     - name: post-urls
  #       run: 
