name: Docker Infra
on: push

jobs:
  deploy-app-docker:
    runs-on: ubuntu-latest
    services:
      app: 
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: post-urls
        run: ping http://localhost:3001/api/user
